baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: charlola.mode
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Recommendations
          url: /recommendations/
          weight: 20
        - name: Projects
          url: /projects/
          weight: 10
        - name: Contact
          url: /contact/
          weight: 40

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Author's Name


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Marko Hammersen
        description: |

          [Moin](https://en.wikipedia.org/wiki/Moin), the name's Marko.\
          I'm an independent embedded-software engineer, husband and dad of three.        
        imageUrl: "/images/me.png"
        imageTitle: me
        imageWidth: 150
        imageHeight: 150
    mainSections:
      - articles

    socialIcons:
        - name: linkedin
          url: "https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjO2LaDub6AAxUMif0HHXNUBE8QFnoECBUQAQ&url=https%3A%2F%2Fde.linkedin.com%2Fin%2Fmarko-hammersen-0836414&usg=AOvVaw0jEhq2oWdTiaQA2JEz48DK&opi=89978449"
        - name: github
          url: "https://github.com/MarkoHammersen"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

